# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration file for Calamares
---
modules-search: [ local ]

instances:
- id:       debian
  module:   shellprocess
  config:   shellprocess_debian.conf

- id:       skel
  module:   shellprocess
  config:   shellprocess_skel.conf

- id:       parched
  module:   shellprocess
  config:   shellprocess_parched.conf


sequence:
- show:
  #- welcome@online
  - welcome
  - locale
  - keyboard
  - partition
#  - packagechooser
#  - netinstall
  - users
  - summary
- exec:
  - partition
  - mount
#  - shellprocess@skel
#  - shellprocess@initialize_pacman
#  - shellprocess@prepacstrap
#  - pacstrap
  #- unpackfs  ---- good
  - machineid
  - locale
  - keyboard
  - localecfg
  - shellprocess@debian
  - fstab
  #- initcpiocfg
  #- initcpio
  - users
  - networkcfg
  - hwclock
  - services-systemd
  #- dracut
  - displaymanager
  - shellprocess@parched
  #- chwd  original parched location marked as good
  #- shellprocess@initialize_pacman
  #- packages original parched location marked as good
  #- shellprocess@removeucode
  #- dracut
  - grubcfg
  - bootloader
#  - shellprocess@reset_mk_hook
#  - services-systemd cachyos position
#  - shellprocess
#  - shellprocess@enable_ufw
  - shellprocessfinal
  - umount
- show:
  - finished

branding: manjaro

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: true

quit-at-end: false
