# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration file for Calamares
---
modules-search: [ local ]

instances:
#- id:       online
#  module:   packages
#  config:   packages_online.conf

#- id:       online
#  module:   welcome
#  config:   welcome_online.conf

- id:       prepacstrap
  module:   shellprocess
  config:   shellprocess_prepacstrap.conf

- id:       postpacstrap
  module:   shellprocess
  config:   shellprocess_postpacstrap.conf

- id:       before-online
  module:   shellprocess
  config:   shellprocess-before-online.conf

- id:       skel
  module:   shellprocess
  config:   shellprocess_skel.conf

- id:       reset_mk_hook
  module:   shellprocess
  config:   shellprocess_reset_mk_hook.conf

- id:       initialize_pacman
  module:   shellprocess
  config:   shellprocess_initialize_pacman.conf

- id:       removeucode
  module:   shellprocess
  config:   shellprocess_removeucode.conf

- id:       enable_ufw
  module:   shellprocess
  config:   shellprocess_enable_ufw.conf

- id:       parched
  module:   shellprocess
  config:   shellprocess_parched.conf


sequence:
- show:
  #- welcome@online
  - welcome
  - locale
  - keyboard
  - partition
#  - packagechooser
  - netinstall
  - users
  - summary
- exec:
  - partition
  - mount
  - shellprocess@skel
  - shellprocess@initialize_pacman
  - shellprocess@prepacstrap
  - pacstrap
  #- unpackfs  ---- good
  - machineid
  - locale
  - keyboard
  - localecfg
  - shellprocess_postpacstrap
  - chwd
  - packages
  - luksbootkeyfile
  - luksopenswaphookcfg
  - fstab
  #- initcpiocfg
  #- initcpio
  - users
  - networkcfg
  - hwclock
  - services-systemd
  #- dracut
  - displaymanager
  - shellprocess@parched
  #- chwd  original parched location marked as good
  #- shellprocess@initialize_pacman
  #- packages original parched location marked as good
  #- shellprocess@removeucode
  #- dracut
  - grubcfg
  - bootloader
#  - shellprocess@reset_mk_hook
#  - services-systemd cachyos position
#  - shellprocess
#  - shellprocess@enable_ufw
  - shellprocessfinal
  - umount
- show:
  - finished

branding: manjaro

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: true

quit-at-end: false
