# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
### pacstrap Module
#
# This module installs the base system and then copies files
# into the installation that will be used in the installed system
#

---
# basePackages is an array of package names to pass to pacstrap
#
basePackages:
  - base
  - base-devel
  - btrfs-progs
  - cryptsetup
  - device-mapper
  - diffutils
  - dosfstools
  - e2fsprogs
  - efibootmgr
  - exfatprogs
  - f2fs-tools
  - grub
  - inetutils
  - iptables-nft
  - jfsutils
  - less
  - linux-cachyos
  - linux-cachyos-headers
  - linux-firmware
  - logrotate
  - lsb-release
  - lvm2
  - man-db
  - man-pages
  - mdadm
  - chwd
  - dracut
  - sddm
  - netctl
  - os-prober
  - perl
  - python
  - s-nail
  - sudo
  - sysfsutils
  - texinfo
  - usbutils
  - which
  - xfsprogs
  - plymouth
  - 7zip
  - a-candy-beauty-icon-theme-git
  - accountsservice
  - alsa-firmware
  - alsa-lib
  - alsa-plugins
  - alsa-utils
  - amd-ucode
  - appimagelauncher
  - arch-install-scripts
  - archinstall
  - archiso
  - arcolinux-arc-kde
  - arcolinux-candy-beauty-plasma-git
  - ark
  - asciinema
  - audiocd-kio
  - awesome-terminal-fonts
  - base
  - base-devel
  - bash-completion
  - bat
  - bind
  - blueberry
  - bluedevil
  - bluez
  - bluez-libs
  - bluez-utils
  - bolt
  - boost-libs
  - breeze
  - breeze-grub
  - breeze-gtk
  - breeze-icons
  - breeze-plymouth
  - broadcom-wl-dkms
  - btop
  - btrfs-progs
  - calamares
  - chaotic-keyring
  - chaotic-mirrorlist
  - chwd
  - clonezilla
  - cryfs
  - cryptsetup
  - cups
  - cups-filters
  - cups-pdf
  - cups-pk-helper
  - ddrescue
  - dex
  - dhclient
  - dhcpcd
  - dialog
  - diffutils
  - dmidecode
  - dmraid
  - dnsmasq
  - dolphin-plugins
  - dosfstools
  - downgrade
  - dracut
  - dracut-hook
  - drkonqi
  - duf
  - e2fsprogs
  - edk2-shell
  - efibootmgr
  - electron
  - encfs
  - ethtool
  - exfatprogs
  - expac
  - f2fs-tools
  - fastfetch
  - fatresize
  - ffmpegthumbnailer
  - ffmpegthumbs
  - flatpak
  - flatpak-kcm
  - floorp-bin
  - freetype2
  - fsarchiver
  - fwupd
  - ghostscript
  - git
  - gnu-netcat
  - gocryptfs
  - gpart
  - gpm
  - gptfdisk
  - grub
  - gsfonts
  - gst-libav
  - gst-plugins-bad
  - gst-plugins-base
  - gst-plugins-good
  - gst-plugins-ugly
  - gstreamer
  - gtk3-classic
  - gutenprint
  - gvfs
  - gvfs-afc
  - gvfs-gphoto2
  - gvfs-mtp
  - gvfs-nfs
  - gvfs-smb
  - gwenview
  - hdparm
  - hplip
  - hw-probe
  - hwinfo
  - hyfetch
  - imagemagick
  - intel-ucode
  - intltool
  - iptables-nft
  - irssi
  - iw
  - iwd
  - jfsutils
  - jsoncpp
  - kate
  - kconfig
  - kcoreaddons
  - kde-gtk-config
  - kde-system-meta
  - kdeconnect
  - kdenetwork-filesharing
  - kdeplasma-addons
  - kgamma
  - ki18n
  - kinfocenter
  - kinit
  - konsole
  - kpmcore
  - krdp
  - kscreen
  - kservice
  - ksshaskpass
  - kwallet-pam
  - kwidgetsaddons
  - laptop-detect
  - less
  - lib32-pipewire
  - libcups
  - libdvdcss
  - libfido2
  - libgsf
  - libmtp
  - libopenraw
  - libpwquality
  - libusb-compat
  - libxinerama
  - linux-ca


#
# postInstallFiles is an array of file names which will be copied into the system
#
# The paths should be relative to the host and the files will be copied to the
# location in the installed system
#
postInstallFiles:
  - "/etc/calamares/scripts/remove-ucode"
  - "/etc/calamares/scripts/enable-ufw"
